You need to have libxbox installed.  Then just run make and supply 
the libxbox build directory, like so:

LIBXBOX_DIR=../libxbox make

Assuming that libxbox.so is installed properly this will build fine.


